services:
  
  server:
    restart: always
    build:
      context: .
      dockerfile: ./server/Dockerfile

    ports:
      - "8080:8080"

    environment:
      HOST_URL: localhost
      DB_URL: mongodb
      DB_PORT: 27017
      PORT: 8080

    networks:
      - videoconf
    depends_on:
      - mongodb

  mongodb:
    restart: always
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - videoconf

  videoconf-client:
    container_name: videoconf-client
    working_dir: /app
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"

  load-balancer:
    image: nginx:latest
    container_name: load-blancer
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - videoconf-client
      - server
    networks:
      - videoconf


volumes:
  mongodb_data_container

networks:
  videoconf:
    driver: bridge